### ISSUE TITLE
Fatal error: Unexpected end of input

### ISSUE THREAD

**Issue by markusfalk** [yargalot/grunt-accessibility#29]
I get this error when using a certain styling: **Fatal error: Unexpected end of input**

I have narrowed down the SCSS that causes the problem:

```SCSS
.contentbox-head {
  .startnext & {
    display: table;
  }
}
.contentbox-heading {
  .startnext & {
    display: table-cell;
  }
}
```

and HTML:

```HTML
<div class="contentbox white">
  <div class="contentbox-head">
    <h2 class="contentbox-heading">Beschriftung</h2>
  </div>
  <div class="contentbox-image">
    <img src="http://imagefoo.dev.webit.de/300x181/bbb/222.png" width="300" height="181" alt="">
  </div>
  <div class="contentbox-content">
    <h3>Tourist Information</h3>
    <p>
      Weit hinten, hinter den Wortbergen, fern der Länder Vokalien und Konsonantien leben die Blindtexte.
    </p>
    <a href="#" class="userlike">Lassen Sie sich beraten</a>
  </div>
</div>
```

It seems the ```display: table-cell``` is causing the accessibility task to exit. The whole setup is here: https://github.com/markusfalk/css-vs-accessibility

Any idea what could cause this error?
